parameters:
  - name: folder_cognito_users
    type: string
  - name: deployConfig
    type: object

stages:
  - ${{ each deployConfig in parameters.deployConfig }}:
      - template: stages/cognito/delete-users.yaml
        parameters:
          stage: ${{ deployConfig.stage }}
          folder_cognito_users: ${{ parameters.folder_cognito_users }}