parameters:
  - name: test
    type: string
    default: test
  - name: deployConfig
    type: object

stages:
  - ${{ each deployConfig in parameters.deployConfig }}:
      - template: stages/set-users.yaml
        parameters:
          stage: ${{ deployConfig.stage }}