parameters:
  - name: test
    type: string
    default: test
  - name: stage
    type: string

stages:
  - stage: Delete_Cognito_User${{ parameters.stage }}
    displayName: Delete Cognito User ${{ parameters.stage }}
    # variables:
    #   - name: deploymentName
    #     value: ${{ replace(parameters['variableGroup'],'-','_') }}
    #   - group: ${{ parameters.commonsVariableGroup }}
    #   - group: ${{ parameters.variableGroup }}
    jobs:
      - deployment: ${{ parameters.stage }}
        displayName: ${{ parameters.stage }}
        environment: DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - checkout: azd

                - task: Bash@3
                  displayName: Delete User
                  inputs:
                    targetType: filePath
                    filePath: azp/scripts/cognito/delete-user-cognito.sh
                  env:
                    POOL_ID: $(POOL_ID)
                    USERNAME: $(USERNAME)