parameters:
  - name: folder_cognito_users
    type: string
  - name: stage
    type: string



stages:
  # Primer Stage para validar los cambios
  - stage: ValidationStage
    jobs:
      - job: ValidateChanges
        displayName: "Validar cambios en archivos específicos"
        variables:
        - name: FOLDER
          value: cognito-delete-users        
        steps:
          - checkout: self
          
          - script: |
              echo "Validando archivos modificados..."

              git diff-tree --no-commit-id --name-only -r HEAD
              MODIFIED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)
              echo $MODIFIED_FILES
              
              if echo "$MODIFIED_FILES" | grep -q "^$FOLDER/users-prod.yaml"; then
                echo "Se detectaron cambios en archivos relevantes."
                echo "##vso[task.setvariable variable=changesDetected]true"
              else
                echo "No se detectaron cambios relevantes."
                echo "##vso[task.setvariable variable=changesDetected]false"

  - stage: ConditionalStage
    dependsOn: ValidationStage
    condition: eq(dependencies.ValidationStage.outputs['ValidateChanges.changesDetected'], 'true')
    jobs:
      - job: RunIfChangesDetected
        displayName: "Ejecutar si hay cambios detectados"
        steps:
          - script: echo "Se han detectado cambios relevantes. Ejecutando Stage Condicional..."