parameters:
  - name: folder_cognito_users
    type: string
  - name: stage
    type: string



stages:
  # Primer Stage para validar los cambios
  - stage: ValidationStage
    jobs:
      - job: ValidateChanges
        displayName: "Validar cambios en archivos específicos"
        variables:
        - name: FOLDER
          value: cognito-delete-users
        - name: system.debug
          value: 'true'
                   
        steps:
          - checkout: self
            fetchDepth: 5
          - checkout: azd

          - script: |
              cd pipes
              echo "Validando archivos modificados..."
              MODIFIED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)
              echo $MODIFIED_FILES
              if echo "$MODIFIED_FILES" | grep -q "^$FOLDER/users-prod.yaml"; then
                echo "Se detectaron cambios en archivos relevantes."
                echo "##vso[task.setvariable variable=changesDetected;isOutput=true;]true"
              else
                echo "No se detectaron cambios relevantes."
                echo "##vso[task.setvariable variable=changesDetected;isOutput=true;]false"
              fi
            name: ValidationScript
            displayName: ValidationScript   

  - stage: ConditionalStage
    dependsOn: ValidationStage
    condition: eq(dependencies.ValidationStage.outputs['ValidateChanges.ValidationScript.changesDetected'], 'true')
    jobs:
      - job: RunIfChangesDetected
        displayName: "Ejecutar si hay cambios detectados"
        steps:
          - script: echo "Se han detectado cambios relevantes. Ejecutando Stage Condicional..."